### ISSUE TITLE
Autopolyploid config file

### ISSUE THREAD

**Issue by awesomedeer** [zhangrengang/SubPhaser#12]
Hey Dr Zhang @zhangrengang 
I was reading your manuscript and wondering how does the config file for autopolyploid genome look like? For example _Medicago sativa_.

**Comment by zhangrengang** [comment]
@awesomedeer The config file for Medicago sativa in the ms:
```
chr1.1  chr1.2  chr1.3  chr1.4
chr2.1  chr2.2  chr2.3  chr2.4
chr3.1  chr3.2  chr3.3  chr3.4
chr4.1  chr4.2  chr4.3  chr4.4
chr5.1  chr5.2  chr5.3  chr5.4
chr6.1  chr6.2  chr6.3  chr6.4
chr7.1  chr7.2  chr7.3  chr7.4
chr8.1  chr8.2  chr8.3  chr8.4
```
The parameters used: `-q 50 -baseline 2 -nsg 2`.
