### ISSUE TITLE
Singularity container fails if environmental variable `R_LIBS_USER` is set

### ISSUE THREAD

**Issue by taprs** [zhangrengang/SubPhaser#25]
Hi!

I was able to finish the pipeline Singularity version but had to reset the path to R libraries manually (I have a custom R library path set in my `.bashrc`). The following was sufficient:

```
export R_LIBS_USER=/share/home/app/bin/miniconda3/envs/SubPhaser/lib/R/library/
```

Maybe it's worth adding that variable to the container recipe.

Also, the `mafft` stage fails if `$TMPDIR` is in other path than `/tmp` (was `/scratch` in my case), I had to specify the bind path manually when running the container. (Could be fixed by adding $TMPDIR to default bindpaths or SINGULARITY_BIND variable?)

Thanks again!
Nikita

**Comment by zhangrengang** [comment]
The image file has been updated by setting the environment:
```
export R_LIBS_USER=/share/home/app/bin/miniconda3/envs/SubPhaser/lib/R/library/:$R_LIBS_USER
export PYTHONPATH=/share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/:$PYTHONPATH
export TMPDIR=/tmp
```
You may test again.

**Comment by taprs** [comment]
Did not test, but I believe that it should resolve the issue. Thank you!
