### ISSUE TITLE
Autopolyploid Validation

### ISSUE THREAD

**Issue by ShadeNiece** [zhangrengang/SubPhaser#40]
Hi Dr. Zhang,

Thank you for such a great tool! I am working with a suspected autotetraploid tree species (2n = 4x = 48), and I ran SubPhaser to essentially support it being auto- due to the lack of subgenome-specific kmers identified. I initially ran SubPhaser with the deafult parameters and it found no differnetial subgenome kmers: "After filtering, remained 0 (0.00%) differential (freq >= 200) and 0 (0.00%) candidate (freq > 0) kmers". 

In [issue #12](https://github.com/zhangrengang/SubPhaser/issues/12) , you recommended using the following parameters for an autopolyploid, Medicago sativa: -q50, -baseline 2, nsg 2. I was wondering if you could please explain the rational behind using those parameters? I ended up trying those exact parameters, and SubPhaser successfully completed. I still think there aren't any valid results since there were only 1023 kmers retained after filtering the initial 26991471 kmers identified and also by looking at the figures generated (please see below). Also, I would assume this is not very many significant subgenome-specific LTR-RTs and that the divergence estimation seems quite recent?
```
118 significant subgenome-specific LTR-RTs
24-11-21 16:21:40 [INFO]        79 SG1-specific LTR-RTs
24-11-21 16:21:40 [INFO]        39 SG2-specific LTR-RTs
24-11-21 16:21:40 [INFO] Summary of overall LTR insertion age (million years):
24-11-21 16:21:40 [INFO]        median: 0.065   95% CI (percentile-based): 0.000-1.541
24-11-21 16:21:40 [INFO] A rough estimation of the divergence–hybridization period: 1.264-0.009 (0.060)
```
<img width="718" alt="image" src="https://github.com/user-attachments/assets/429bf527-9035-4349-b96a-08cb9ed2d62b">
<img width="642" alt="image" src="https://github.com/user-attachments/assets/e141a890-6c12-497b-bbc0-b37e4feb51d4">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/62710ebe-0d20-4a47-be8c-30369e3e40b9">
<img width="710" alt="image" src="https://github.com/user-attachments/assets/cbc2eb3f-f03a-499a-8089-65c4ecc04a1d">
<img width="712" alt="image" src="https://github.com/user-attachments/assets/e4d0c359-dfba-47f7-85f3-8e85bb0ee247">

Sorry for the long message, but any advice or commentary is appreciated very much!
Thank you, Shade

**Comment by zhangrengang** [comment]
Yes, there aren't any valid results. The parameter `-q 50 -baseline 2 -nsg 2` is what I used for the autopolyploid Medicago sativa in our paper, but in fact, it did not work. `-q 50` is to retrieve more differential kmers than the default `-q 200`, `-nsg 2` is to expect two subgenomes while there are four columns in the config file (by default `nsg` will automatically be 4). `-baseline 2` is to compare the frequency of kmers between the first (index=0) and the third (2) chromosome sets, as the second (1) is assumed to be homologous to the first (assuming no difference between this two sets).
Your assumption about LTR-RTs is not reasonable, because the upstream analysis of differential kmers is failed in fact.

**Comment by ShadeNiece** [comment]
Thank you for the feedback! Do you have any other recomendations for similar tools that are targeted towards autopolyploids? It seems like there's generally a lack of similar resources for autopolyploids. Regardless, I still really appreciate your help, and our lab will definitely be using SubPhaser on any future allopolyploid projects!

**Comment by zhangrengang** [comment]
@ShadeNiece You can use a phylogeny-based method: http://doi.org/10.1093/bib/bbad513.

**Comment by ShadeNiece** [comment]
Thank you for the feedback!
